version: '3.0'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
    hostname: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.0
    hostname: kibana
    ports:
      - 5601:5601
    links:
      - elasticsearch

  logstash-producer:
    image: 00000000000.dkr.ecr.eu-west-2.amazonaws.com/logstash_producer:latest
    hostname: logstash-producer
    environment:
      LOG_LEVEL: error

  logstash-consumer:
    image: 00000000000.dkr.ecr.eu-west-2.amazonaws.com/logstash_consumer:latest
    hostname: logstash-consumer
    environment:
      LOG_LEVEL: error
    links:
      - elasticsearch
