version: '3.7'

services:
  zookeeper:
    image: zookeeper:3.4.9
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zookeeper:2888:3888

  kafka:
    image: confluentinc/cp-kafka:5.3.0
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  riemannfront:
    image: riemannio/riemann:0.3.3
    hostname: riemannfront
    volumes:
      - ./riemannfront.config:/etc/riemann.config
    environment:
      - HOST_IP=${DOCKER_HOST_IP:-127.0.0.1}
    ports:
      - "3003:3003" # graphite port (shifted to avoid conflict with carbon-clickhouse)
    depends_on:
      - kafka

  riemannback:
    image: riemannio/riemann:0.3.3
    hostname: riemannback
    volumes:
      - ./riemannfront.config:/etc/riemann.config
    environment:
      - HOST_IP=${DOCKER_HOST_IP:-127.0.0.1}
    depends_on:
      - kafka

  clickhouse:
    image: yandex/clickhouse-server
    hostname: clickhouse
    volumes:
      - "./rollup.xml:/etc/clickhouse-server/config.d/rollup.xml"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    depends_on:
      - zookeeper

  carbon-clickhouse:
    image: lomik/carbon-clickhouse:v0.10.2
    hostname: carbon-clickhouse
    volumes:
      - "./data/carbon-clickhouse:/data/carbon-clickhouse"
      - "./carbon-clickhouse.conf:/etc/carbon-clickhouse/carbon-clickhouse.conf"
    ports:
      - "2003:2003" # plain tcp
      - "2004:2004" # pickle
      - "2006:2006" # prometheus remote write
    depends_on:
      - clickhouse

  collectd:
    image: collectd
    hostname: collectd
    volumes:
        - ./collectd.conf:/etc/collectd/collectd.conf
    depends_on:
      - kafka
      - riemannfront
