version: '3.3'

services:
  zookeeper:
    image: zookeeper:3.4.9
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888

  kafka:
    image: confluentinc/cp-kafka:5.3.0
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICVERSION}
    hostname: elasticsearch
    ports: 
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTICVERSION}
    hostname: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  logstashfront:
    image: docker.elastic.co/logstash/logstash:7.4.0
    hostname: logstashfront
    volumes:
      - ./logstashfront.conf:/logstashfront.conf
    ports:
      - "5001:5001"
    entrypoint: logstash -f /logstashfront.conf
    depends_on:
      - kafka

  logstashback:
    image: docker.elastic.co/logstash/logstash:7.4.0
    hostname: logstashback
    volumes:
      - ./logstashback.conf:/logstashback.conf
    entrypoint: logstash -f /logstashback.conf
    depends_on:
      - elasticsearch

  logger:
    image: ubuntu
    hostname: logger
    environment:
      LOGINTERVAL: ${LOGINTERVAL}
      LOGHOST: ${LOGHOST}
    volumes:
      - "./logger.sh:/logger.sh"
      - "./logfile:/logfile"
    entrypoint: /logger.sh
    depends_on:
      - logstashfront
