version: '3.7'

services:
  zookeeper:
    image: zookeeper:3.4.9
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zookeeper:2888:3888

  kafka:
    image: confluentinc/cp-kafka:5.3.0
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  riemann:
    image: riemannio/riemann:0.3.3
    hostname: riemann
    volumes:
      - ./riemann.config:/etc/riemann.config
    environment:
      - HOST_IP=${DOCKER_HOST_IP:-127.0.0.1}
    depends_on:
      - kafka
      - elasticsearch

  clickhouse:
    image: yandex/clickhouse-server
    hostname: clickhouse
    ports:
      - 8123:8123
      - 9000:9000
      - 9009:9009
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - zookeeper

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
    hostname: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.0
    hostname: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  graphite-clickhouse:
    image: mosquito/graphite-clickhouse
    hostname: graphite-clickhouse
    environment:
      CLICKHOUSE_URL: http://clickhouse:8123
    ports:
      - 9090:9090
    depends_on:
      - clickhouse

  carbon-clickhouse:
    image: mosquito/carbon-clickhouse
    hostname: carbon-clickhouse
    environment:
      CLICKHOUSE_URL: http://clickhouse:8123
    ports:
      - 2003:2003
      - 2004:2004
      - 2005:2005
    depends_on:
      - clickhouse

  carbonapi:
    image: mosquito/carbonapi
    hostname: carbonapi
    ports:
      - 8080:8080
    environment:
      CONCURENCY: 20
      CACHE_TYPE: mem
      UPSTREAMS_BACKENDS: http://graphite-clickhouse:9090/
      LISTEN: "0.0.0.0:8080"
    depends_on:
      - graphite-clickhouse

  tabix:
    image: spoonest/clickhouse-tabix-web-client
    hostname: tabix
    links:
      - clickhouse
    ports:
      - 8090:80

  grafana:
    image: grafana/grafana
    hostname: grafana
    links:
      - carbonapi
    ports:
      - 3000:3000
    environment:
      GF_SERVER_ROOT_URL: http://${DOCKER_HOST_IP:-127.0.0.1}:3000
      GF_SECURITY_ADMIN_PASSWORD: secret
    depends_on:
      - carbonapi

  logstash-post:
    image: docker.elastic.co/logstash/logstash:7.3.1
    hostname: logstash-post
    depends_on:
    - elasticsearch
